import React from "react";
import { api } from "../api.js";
import { Card, StatCard, Loading, ErrorBox, useApi } from "../components/ui.jsx";

function percent(value, digits = 1) {
  const n = Number(value);

  if (!Number.isFinite(n)) return "N/A";

  return `${(n * 100).toFixed(digits)}%`;
}

function number(value, digits = 1) {
  const n = Number(value);

  if (!Number.isFinite(n)) return "N/A";

  return n.toFixed(digits);
}

function MetricExplanation({ title, value, description }) {
  return (
    <div className="rounded-lg border border-border p-4">
      <div className="text-xs text-muted uppercase tracking-wide">
        {title}
      </div>

      <div className="text-xl font-bold mt-1">
        {value}
      </div>

      <p className="text-xs text-muted mt-2 leading-relaxed">
        {description}
      </p>
    </div>
  );
}

export default function LeadTimeAnalytics() {
  const {
    data,
    loading,
    error,
  } = useApi(() => api.leadTime(), []);

  if (loading) return <Loading />;
  if (error) return <ErrorBox error={error} />;

  const result = data || {};

  const strongMatches =
    result.n_strong_matches ??
    result.n_matched_to_ground_truth ??
    0;

  const moderateMatches =
    result.n_moderate_matches ?? 0;

  const alertedMatched =
    result.n_alerted_and_matched ?? 0;

  const earlyDetections =
    result.n_early_detections ?? 0;

  return (
    <div className="space-y-5">

      {/* Header */}
      <div>
        <h1 className="text-xl font-bold">
          Lead-Time Analytics
        </h1>

        <p className="text-sm text-muted mt-1">
          Central research question: how early can suspicious
          transaction behaviour be identified?
        </p>
      </div>

      {/* Evaluation scope */}
      <Card title="Evaluation Scope">

        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">

          <MetricExplanation
            title="AMLSim Alerts"
            value={result.ground_truth_rings ?? 100}
            description="Known AMLSim alert events used as ground truth."
          />

          <MetricExplanation
            title="Ring Candidates"
            value={result.n_candidates ?? 142}
            description="Suspicious ring candidates generated by the pipeline."
          />

          <MetricExplanation
            title="Strict Matches"
            value={strongMatches}
            description="Candidates sharing at least two participant accounts and overlapping transaction time."
          />

          <MetricExplanation
            title="Alerted + Matched"
            value={alertedMatched}
            description="Matched candidates that actually crossed the configured risk threshold."
          />

        </div>

      </Card>

      {/* Primary metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">

        <StatCard
          label="Strict Ring Detection Rate"
          value={percent(result.ring_detection_rate, 1)}
        />

        <StatCard
          label="Early Detection Rate"
          value={percent(result.early_detection_rate, 1)}
        />

        <StatCard
          label="Mean Lead Time"
          value={
            result.mean_lead_time_windows != null
              ? `${number(result.mean_lead_time_windows)} windows`
              : "N/A"
          }
        />

        <StatCard
          label="Median Lead Time"
          value={
            result.median_lead_time_windows != null
              ? `${number(result.median_lead_time_windows)} windows`
              : "N/A"
          }
        />

        <StatCard
          label="False Warning Rate"
          value={percent(
            result.false_warning_rate_candidates,
            1
          )}
        />

        <StatCard
          label="Early Detections"
          value={`${earlyDetections} / ${alertedMatched}`}
        />

      </div>

      {/* Current result interpretation */}
      <Card title="Current Result">

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

          <MetricExplanation
            title="Ring Detection"
            value={percent(result.ring_detection_rate, 1)}
            description={`${result.unique_ground_truth_rings_detected ?? 0} unique AMLSim ring(s) were detected under the strict matching rule.`}
          />

          <MetricExplanation
            title="Early Warning"
            value={percent(result.early_detection_rate, 1)}
            description={`${earlyDetections} matched alerted candidate(s) received a warning before the AMLSim observable event.`}
          />

          <MetricExplanation
            title="Lead Time"
            value={
              result.mean_lead_time_windows != null
                ? `${number(result.mean_lead_time_windows)} windows`
                : "N/A"
            }
            description="Positive values indicate earlier warning; negative values indicate warning after the defined observable event."
          />

        </div>

      </Card>

      {/* Completion-based comparison */}
      {(result.extended_n_alerted_and_matched != null ||
        result.extended_early_detection_rate != null) && (
        <Card title="Completion-Based Secondary View">

          <p className="text-xs text-muted mb-4 leading-relaxed">
            A secondary view treats the latest AMLSim alert transaction as
            the end of the known alert lifecycle. This does not replace the
            strict baseline evaluation.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

            <MetricExplanation
              title="Matched Candidates"
              value={
                result.extended_n_alerted_and_matched ?? "N/A"
              }
              description="Alerted candidates linked under the extended evaluation."
            />

            <MetricExplanation
              title="Early Detection"
              value={percent(
                result.extended_early_detection_rate,
                1
              )}
              description="Warnings occurring before the end of the known AMLSim alert lifecycle."
            />

            <MetricExplanation
              title="Mean Lead Time"
              value={
                result.extended_mean_lead_time_windows != null
                  ? `${number(
                      result.extended_mean_lead_time_windows
                    )} windows`
                  : "N/A"
              }
              description="Completion-based warning lead time."
            />

          </div>

        </Card>
      )}

      {/* Match quality */}
      <Card title="Ground-Truth Linkage">

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

          <MetricExplanation
            title="Strong Matches"
            value={strongMatches}
            description="At least two shared accounts plus temporal overlap."
          />

          <MetricExplanation
            title="Moderate Matches"
            value={moderateMatches}
            description="At least two shared accounts with a nearby temporal gap; reported separately."
          />

          <MetricExplanation
            title="Matched Candidate Rate"
            value={percent(
              result.candidate_match_rate,
              1
            )}
            description="Strictly matched candidates divided by all generated candidates."
          />

        </div>

      </Card>

      {/* Research interpretation */}
      <Card title="Research Interpretation">

        <div className="space-y-3 text-sm">

          <p className="text-muted leading-relaxed">
            Lead-time evaluation measures whether a suspicious-ring
            candidate becomes actionable before the corresponding AMLSim
            ground-truth event reaches the defined observable point.
          </p>

          <div className="rounded-lg border border-border p-4">

            <div className="text-xs font-semibold uppercase tracking-wide">
              Current limitation
            </div>

            <p className="text-xs text-muted mt-2 leading-relaxed">
              The current strict evaluation has a low candidate-to-ground-truth
              linkage rate. Therefore, the early-detection statistic is based
              on a very small number of matched alerted candidates and should
              not be interpreted as a definitive estimate of system-wide
              early-warning capability.
            </p>

          </div>

          <div className="rounded-lg border border-border p-4">

            <div className="text-xs font-semibold uppercase tracking-wide">
              Interpretation of negative lead time
            </div>

            <p className="text-xs text-muted mt-2 leading-relaxed">
              A negative lead-time value means that the candidate's warning
              occurred after the defined AMLSim observable event. Positive
              lead time indicates warning before that event.
            </p>

          </div>

        </div>

      </Card>

      {/* Methodology */}
      <Card title="Evaluation Rule">

        <div className="text-xs text-muted leading-relaxed space-y-2">

          <p>
            <span className="font-medium text-white">
              Strong / strict match:
            </span>{" "}
            at least two shared participant accounts and overlapping
            transaction intervals.
          </p>

          <p>
            <span className="font-medium text-white">
              Moderate linkage:
            </span>{" "}
            at least two shared accounts with a temporal gap of up to
            10 days. Moderate linkage is reported separately and does not
            replace the strict evaluation.
          </p>

          <p>
            <span className="font-medium text-white">
              Lead-time convention:
            </span>{" "}
            positive values mean earlier warning; negative values mean
            later warning.
          </p>

        </div>

      </Card>

      {/* Disclaimer */}
      <div className="rounded-lg border border-border px-4 py-3">

        <div className="text-xs font-semibold uppercase tracking-wide">
          Important
        </div>

        <p className="text-xs text-muted mt-1 leading-relaxed">
          Lead-time results are evaluation metrics for the computational
          system. They should not be interpreted as proof that a real-world
          laundering event was detected before investigators or regulators
          could observe it.
        </p>

      </div>

    </div>
  );
}